### ISSUE TITLE
Improve formatting of tooltips and other aspects of charts

### ISSUE THREAD

**Issue by neuroactive** [koroonakaart/koroonakaart#229]
There are a number of improvements that could be made to the chart tooltips to improve their appearance and clarity, as well as various other improvements that could be made to the charts. Many aspects of the charts aren't localised and the axis labels are hard to read.

Improvements to implement for tooltips:

- [x] Fix bug in tooltips where entries are shown for lines which have been deselected
- [x] Fix bug in "Tests per day" chart where values are missing in some tooltips when not at default zoom level (see #240)
- [ ] Fix bug in "New cases per day" chart where values shown in tooltip are incorrect
- [x] Replace coloured text labels with coloured markers to the left-hand side of the text label for better legibility
- [x] Use shared tooltips in preference to split tooltips
- [ ] Localise dates in tooltips correctly and consistently
- [x] Right-align numbers on shared tooltips for easier comparison
- [x] Implement appropriate precision for numbers (see #224)
- [ ] Ensure there is a space between text labels and numbers
- [ ] Review font size of tooltips
- [x] Remove duplicated percentage signs in "Tests per day" chart  (see #106)
- [ ] Show "Week beginning ..." in title of tooltip when Highcharts is showing weekly data

Other miscellaneous improvements to the charts that we should implement:

- [ ] Use localised "human-readable" dates in the X-axis rather than "computer-format" dates
- [ ] Use a circle marker symbol for charts with multiple lines rather than different-shaped markers
- [ ] Localise context menu, zoom selector, and range (date) selector, including the dates themselves
- [ ] Implement European-style date format in date selector
- [ ] Review whether there is a more user-friendly date selector widget available
- [ ] Review font size of axis labels
- [ ] Review chart titles (see #105)
- [ ] Review legend text
- [ ] Make design of secondary chart buttons (Linear, Logarithmic, etc) consistent with Zoom-related buttons
- [ ] Add "navigator" date selectors to all time series charts
- [ ] Improve typography on textual labels on map
- [ ] Improve choice of colours to represent "male" and "female"

![tooltips](https://user-images.githubusercontent.com/22959023/115979537-2683a480-a58f-11eb-93bc-84de236baf5d.png)

![axis-label](https://user-images.githubusercontent.com/22959023/115979432-96ddf600-a58e-11eb-99d1-94215ccf9af4.png)

**Comment by sarnane** [comment]
Hello!
If you want, I can help out with this.

**Comment by neuroactive** [comment]
@sarnane Thanks for the offer. I have actually been working on these and am going to be pushing some code live soon which fixes quite a lot of these issues. Perhaps I can liaise with you here after that is done and we can see what is remaining.

**Comment by neuroactive** [comment]
@sarnane So I have sent some code live which fix various various items on these checklists. Some of the other items are mostly implemented, but I'm not going to tick them off until every chart on the page has been covered.

If you would like something to work on, it would be very helpful if you could update the way the "Total Tests" chart is implemented (which I have just renamed in the English version from "Cumulative Tests"), so that it matches the way the "Cases per 100,000 population" chart has been done. If you implement things in the same way, this will fix various issues with the tooltip, including the localisation of the dates, and will also improve the date format in the x-axis and add a "navigator" date selector underneath the chart.

Another useful job would be to update the style of the secondary buttons (e.g. "Linear", "Logarithmic", etc) so that they exactly match the visual style of Zoom selector buttons, for both the currently-selected and unselected items. This will look a bit better and using the same style for both should make it easier for users to recognise that these are menus. You could also remove the word "Zoom" from the Zoom selector menu, as it's probably unnecessary, but if you do so, try to make sure the zoom selector buttons align to the left-hand side of the chart.

I am going to focus on improving the data update process for the moment as there are some issues with that which are affecting the stability of the site. Just let me know if you have any questions or want to discuss anything.
